---
prepare_configs:
  - name: "int-app-alpha"
    description: "Alpha application"
    organization: 1
  - name: "int-app-beta"
    description: "Beta application"
    organization: 1
  - name: "int-app-gamma"
    description: "Gamma seed"
    organization: 1

expected_config:
  name: "int-app-alpha"
  description: "Alpha application"
  organization: 1
