"""
API v2 NotificationTemplate dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the controller OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ....platform.base_transform import BaseTransformMixin
from ....platform.types import EndpointOperation, TransformContext


@dataclass
class APINotificationTemplate_v2(BaseTransformMixin):
    """API v2 representation of a controller notification_template."""

    name: str
    organization: int
    notification_type: str
    description: Optional[str] = None
    notification_configuration: Optional[Any] = None
    messages: Optional[Any] = None


class NotificationTemplateTransformMixin_v2(BaseTransformMixin):
    """Transform mixin for NotificationTemplate API v2."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APINotificationTemplate_v2":
        api_data: Dict[str, Any] = {}

        for field in (
            "name",
            "description",
            "organization",
            "notification_type",
            "notification_configuration",
            "messages",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in ():
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APINotificationTemplate_v2(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/v2/notification_templates/",
                method="POST",
                fields=["name", "description", "organization", "notification_type", "notification_configuration", "messages"],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/v2/notification_templates/{id}/",
                method="PATCH",
                fields=["name", "description", "organization", "notification_type", "notification_configuration", "messages"],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/v2/notification_templates/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/v2/notification_templates/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/v2/notification_templates/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ....ansible_models.notification_template import AnsibleNotificationTemplate

        return AnsibleNotificationTemplate(
            name=api_data.get("name"),
            description=api_data.get("description"),
            organization=api_data.get("organization"),
            notification_type=api_data.get("notification_type"),
            notification_configuration=api_data.get("notification_configuration"),
            messages=api_data.get("messages"),
        )
