---
- name: Cleanup — delete workflow_job_template (connection local)
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    wjt_name_local: "Molecule Test WJT Local"
    gateway_hostname: "http://127.0.0.1:8000"
    gateway_username: "mock"
    gateway_password: "testpass"
    gateway_validate_certs: false
  tasks:
    - name: Delete (connection local)
      ansible.platform.workflow_job_template:
        name: "{{ wjt_name_local }}"
        state: absent
        gateway_hostname: "{{ gateway_hostname }}"
        gateway_username: "{{ gateway_username }}"
        gateway_password: "{{ gateway_password }}"
        gateway_validate_certs: "{{ gateway_validate_certs }}"
      failed_when: false
      vars:
        ansible_connection: local

    - name: Remove manager survive flag
      ansible.builtin.file:
        path: /tmp/ap/.survive
        state: absent
      vars:
        ansible_connection: local

- name: Cleanup — delete workflow_job_template (http direct)
  hosts: localhost
  connection: ansible.platform.http
  gather_facts: false
  vars:
    wjt_name_http_direct: "Molecule Test WJT HTTP Direct"
    gateway_hostname: "http://127.0.0.1:8000"
    gateway_username: "mock"
    gateway_password: "testpass"
    gateway_validate_certs: false
    ansible_platform_use_persistent_connection: false
  tasks:
    - name: Delete (http direct)
      ansible.platform.workflow_job_template:
        name: "{{ wjt_name_http_direct }}"
        state: absent
      failed_when: false

    - name: Remove manager survive flag
      ansible.builtin.file:
        path: /tmp/ap/.survive
        state: absent
      vars:
        ansible_connection: local

- name: Cleanup — delete workflow_job_template (http persistent)
  hosts: localhost
  connection: ansible.platform.http
  gather_facts: false
  vars:
    wjt_name_http_persistent: "Molecule Test WJT HTTP Persistent"
    gateway_hostname: "http://127.0.0.1:8000"
    gateway_username: "mock"
    gateway_password: "testpass"
    gateway_validate_certs: false
    ansible_platform_use_persistent_connection: true
  tasks:
    - name: Delete (http persistent)
      ansible.platform.workflow_job_template:
        name: "{{ wjt_name_http_persistent }}"
        state: absent
      failed_when: false

    - name: Remove manager survive flag
      ansible.builtin.file:
        path: /tmp/ap/.survive
        state: absent
      vars:
        ansible_connection: local
...
