"""
API v1 AuthenticatorMap dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIAuthenticatorMap_v1(BaseTransformMixin):
    """API v1 representation of a gateway authenticator_map."""

    name: Optional[str] = None
    authenticator: Optional[int] = None
    triggers: Optional[Any] = None
    map_type: Optional[str] = None
    role: Optional[str] = None
    organization: Optional[str] = None
    team: Optional[str] = None
    revoke: Optional[bool] = None
    order: Optional[int] = None
    id: Optional[int] = None  # read-only
    url: Optional[str] = None  # read-only
    related: Optional[Dict[str, Any]] = None  # read-only
    summary_fields: Optional[Dict[str, Any]] = None  # read-only
    created: Optional[str] = None  # read-only
    created_by: Optional[int] = None  # read-only
    modified: Optional[str] = None  # read-only
    modified_by: Optional[int] = None  # read-only


class AuthenticatorMapTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for AuthenticatorMap API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIAuthenticatorMap_v1":
        api_data: Dict[str, Any] = {}

        for field in (
            "name",
            "authenticator",
            "map_type",
            "role",
            "organization",
            "team",
            "revoke",
            "triggers",
            "order",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in ("id", "url", "related", "summary_fields", "created", "created_by", "modified", "modified_by"):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIAuthenticatorMap_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/gateway/v1/authenticator_maps/",
                method="POST",
                fields=["name", "authenticator", "map_type", "role", "organization", "team", "revoke", "triggers", "order"],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/gateway/v1/authenticator_maps/{id}/",
                method="PATCH",
                fields=["name", "authenticator", "map_type", "role", "organization", "team", "revoke", "triggers", "order"],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/gateway/v1/authenticator_maps/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/authenticator_maps/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/authenticator_maps/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.authenticator_maps import AnsibleAuthenticatorMaps

        return AnsibleAuthenticatorMaps(
            name=api_data.get("name"),
            authenticator=api_data.get("authenticator"),
            map_type=api_data.get("map_type"),
            role=api_data.get("role"),
            organization=api_data.get("organization"),
            team=api_data.get("team"),
            revoke=api_data.get("revoke"),
            triggers=api_data.get("triggers"),
            order=api_data.get("order"),
            id=api_data.get("id"),
            url=api_data.get("url"),
            related=api_data.get("related"),
            summary_fields=api_data.get("summary_fields"),
            created=api_data.get("created"),
            created_by=api_data.get("created_by"),
            modified=api_data.get("modified"),
            modified_by=api_data.get("modified_by"),
        )
