"""
API v1 AuthenticatorUser dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIAuthenticatorUser_v1(BaseTransformMixin):
    """API v1 representation of a gateway authenticator_user."""

    pass


class AuthenticatorUserTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for AuthenticatorUser API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIAuthenticatorUser_v1":
        api_data: Dict[str, Any] = {}

        for field in ():
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in ():
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIAuthenticatorUser_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "get": EndpointOperation(
                path="/api/gateway/v1/authenticator_users/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/authenticator_users/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.authenticator_user import AnsibleAuthenticatorUser

        return AnsibleAuthenticatorUser()
