"""
API v1 FeatureFlag dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIFeatureFlag_v1(BaseTransformMixin):
    """API v1 representation of a gateway feature_flag."""

    name: Optional[str] = None
    value: Optional[str] = None
    id: Optional[int] = None  # read-only
    toggle_type: Optional[str] = None  # read-only
    condition: Optional[str] = None  # read-only
    description: Optional[str] = None  # read-only
    required: Optional[bool] = None  # read-only
    support_level: Optional[str] = None  # read-only
    visibility: Optional[bool] = None  # read-only
    labels: Optional[List[Any]] = None  # read-only


class FeatureFlagTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for FeatureFlag API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIFeatureFlag_v1":
        api_data: Dict[str, Any] = {}

        for field in ("name", "value"):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in ("id", "toggle_type", "condition", "description", "required",
                   "support_level", "visibility", "labels"):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIFeatureFlag_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "update": EndpointOperation(
                path="/api/gateway/v1/feature_flags/{id}/",
                method="PATCH",
                fields=["value"],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/feature_flags/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/feature_flags/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.feature_flag import AnsibleFeatureFlag

        return AnsibleFeatureFlag(
            name=api_data.get("name"),
            value=api_data.get("value"),
            id=api_data.get("id"),
            toggle_type=api_data.get("toggle_type"),
            condition=api_data.get("condition"),
            description=api_data.get("description"),
            required=api_data.get("required"),
            support_level=api_data.get("support_level"),
            visibility=api_data.get("visibility"),
            labels=api_data.get("labels"),
        )
