"""
API v1 JobTemplate dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the platform OpenAPI spec.
Manually updated to support migration from awx.awx/ansible.controller.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext

logger = logging.getLogger(__name__)


@dataclass
class APIJobTemplate_v1(BaseTransformMixin):
    """API v1 representation of a controller job_template."""

    name: Optional[str] = None
    description: Optional[str] = None
    job_type: Optional[str] = None
    inventory: Optional[int] = None
    project: Optional[int] = None
    playbook: Optional[str] = None
    scm_branch: Optional[str] = None
    forks: Optional[int] = None
    limit: Optional[str] = None
    verbosity: Optional[int] = None
    extra_vars: Optional[str] = None
    job_tags: Optional[str] = None
    force_handlers: Optional[bool] = None
    skip_tags: Optional[str] = None
    start_at_task: Optional[str] = None
    timeout: Optional[int] = None
    use_fact_cache: Optional[bool] = None
    execution_environment: Optional[int] = None
    host_config_key: Optional[str] = None
    ask_scm_branch_on_launch: Optional[bool] = None
    ask_diff_mode_on_launch: Optional[bool] = None
    ask_variables_on_launch: Optional[bool] = None
    ask_limit_on_launch: Optional[bool] = None
    ask_tags_on_launch: Optional[bool] = None
    ask_skip_tags_on_launch: Optional[bool] = None
    ask_job_type_on_launch: Optional[bool] = None
    ask_verbosity_on_launch: Optional[bool] = None
    ask_inventory_on_launch: Optional[bool] = None
    ask_credential_on_launch: Optional[bool] = None
    ask_execution_environment_on_launch: Optional[bool] = None
    ask_labels_on_launch: Optional[bool] = None
    ask_forks_on_launch: Optional[bool] = None
    ask_job_slice_count_on_launch: Optional[bool] = None
    ask_timeout_on_launch: Optional[bool] = None
    ask_instance_groups_on_launch: Optional[bool] = None
    survey_enabled: Optional[bool] = None
    become_enabled: Optional[bool] = None
    diff_mode: Optional[bool] = None
    allow_simultaneous: Optional[bool] = None
    job_slice_count: Optional[int] = None
    webhook_service: Optional[str] = None
    webhook_credential: Optional[int] = None
    prevent_instance_group_fallback: Optional[bool] = None
    opa_query_path: Optional[str] = None

    # Read-only
    id: Optional[int] = None
    created: Optional[str] = None
    modified: Optional[str] = None
    url: Optional[str] = None


def _resolve_fk(manager, endpoint: str, lookup_field: str, value) -> Optional[int]:
    """Resolve a name or id to an integer id."""
    if value is None:
        return None
    if str(value).isdigit():
        return int(value)
    try:
        return manager.lookup_resource_id(endpoint, lookup_field, str(value))
    except Exception:
        return None


_SIMPLE_FIELDS = (
    "playbook",
    "scm_branch",
    "forks",
    "limit",
    "verbosity",
    "job_tags",
    "force_handlers",
    "skip_tags",
    "start_at_task",
    "timeout",
    "use_fact_cache",
    "host_config_key",
    "ask_scm_branch_on_launch",
    "ask_diff_mode_on_launch",
    "ask_variables_on_launch",
    "ask_limit_on_launch",
    "ask_tags_on_launch",
    "ask_skip_tags_on_launch",
    "ask_job_type_on_launch",
    "ask_verbosity_on_launch",
    "ask_inventory_on_launch",
    "ask_credential_on_launch",
    "ask_execution_environment_on_launch",
    "ask_labels_on_launch",
    "ask_forks_on_launch",
    "ask_job_slice_count_on_launch",
    "ask_timeout_on_launch",
    "ask_instance_groups_on_launch",
    "survey_enabled",
    "become_enabled",
    "diff_mode",
    "allow_simultaneous",
    "job_slice_count",
    "webhook_service",
    "prevent_instance_group_fallback",
    "opa_query_path",
)


class JobTemplateTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for JobTemplate API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIJobTemplate_v1":
        api_data: Dict[str, Any] = {}
        manager = context.manager if isinstance(context, TransformContext) else context.get("manager")
        op = getattr(context, "operation", None) if isinstance(context, TransformContext) else context.get("operation")

        name = getattr(ansible_instance, "name", None)
        new_name = getattr(ansible_instance, "new_name", None)
        job_type = getattr(ansible_instance, "job_type", None)
        description = getattr(ansible_instance, "description", None)

        if op == "create":
            api_data["name"] = new_name or name
        elif op == "update":
            if new_name is not None:
                api_data["name"] = new_name
            elif name is not None:
                api_data["name"] = name
        else:
            if name is not None:
                api_data["name"] = name

        if description is not None:
            api_data["description"] = description
        if job_type is not None:
            api_data["job_type"] = job_type

        # Resolve reference fields (name → ID)
        inventory = getattr(ansible_instance, "inventory", None)
        if inventory is not None and manager:
            resolved = _resolve_fk(manager, "inventories", "name", inventory)
            if resolved is not None:
                api_data["inventory"] = resolved

        project = getattr(ansible_instance, "project", None)
        organization = getattr(ansible_instance, "organization", None)
        if project is not None and manager:
            if organization is not None:
                org_id = _resolve_fk(manager, "organizations", "name", organization)
                if org_id is not None:
                    try:
                        project_results = manager.execute(
                            operation="find",
                            module_name="project",
                            ansible_data={"name": project, "organization": org_id},
                        )
                        if project_results and project_results.get("id"):
                            api_data["project"] = project_results["id"]
                    except Exception:
                        resolved = _resolve_fk(manager, "projects", "name", project)
                        if resolved is not None:
                            api_data["project"] = resolved
                else:
                    resolved = _resolve_fk(manager, "projects", "name", project)
                    if resolved is not None:
                        api_data["project"] = resolved
            else:
                resolved = _resolve_fk(manager, "projects", "name", project)
                if resolved is not None:
                    api_data["project"] = resolved

        ee = getattr(ansible_instance, "execution_environment", None)
        if ee is not None and manager:
            resolved = _resolve_fk(manager, "execution_environments", "name", ee)
            if resolved is not None:
                api_data["execution_environment"] = resolved

        wh_cred = getattr(ansible_instance, "webhook_credential", None)
        if wh_cred is not None and manager:
            resolved = _resolve_fk(manager, "credentials", "name", wh_cred)
            if resolved is not None:
                api_data["webhook_credential"] = resolved

        # extra_vars: serialize dict to JSON string for the API
        extra_vars = getattr(ansible_instance, "extra_vars", None)
        if extra_vars is not None:
            if isinstance(extra_vars, dict):
                api_data["extra_vars"] = json.dumps(extra_vars)
            else:
                api_data["extra_vars"] = str(extra_vars)

        # Simple 1:1 fields
        for field in _SIMPLE_FIELDS:
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        # Read-only fields (pass through if present)
        for ro in ("id", "created", "modified", "url"):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIJobTemplate_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/controller/v2/job_templates/",
                method="POST",
                fields=[
                    "name",
                    "description",
                    "job_type",
                    "inventory",
                    "project",
                    "playbook",
                    "scm_branch",
                    "forks",
                    "limit",
                    "verbosity",
                    "extra_vars",
                    "job_tags",
                    "force_handlers",
                    "skip_tags",
                    "start_at_task",
                    "timeout",
                    "use_fact_cache",
                    "execution_environment",
                    "host_config_key",
                    "ask_scm_branch_on_launch",
                    "ask_diff_mode_on_launch",
                    "ask_variables_on_launch",
                    "ask_limit_on_launch",
                    "ask_tags_on_launch",
                    "ask_skip_tags_on_launch",
                    "ask_job_type_on_launch",
                    "ask_verbosity_on_launch",
                    "ask_inventory_on_launch",
                    "ask_credential_on_launch",
                    "ask_execution_environment_on_launch",
                    "ask_labels_on_launch",
                    "ask_forks_on_launch",
                    "ask_job_slice_count_on_launch",
                    "ask_timeout_on_launch",
                    "ask_instance_groups_on_launch",
                    "survey_enabled",
                    "become_enabled",
                    "diff_mode",
                    "allow_simultaneous",
                    "job_slice_count",
                    "webhook_service",
                    "webhook_credential",
                    "prevent_instance_group_fallback",
                    "opa_query_path",
                ],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/controller/v2/job_templates/{id}/",
                method="PATCH",
                fields=[
                    "name",
                    "description",
                    "job_type",
                    "inventory",
                    "project",
                    "playbook",
                    "scm_branch",
                    "forks",
                    "limit",
                    "verbosity",
                    "extra_vars",
                    "job_tags",
                    "force_handlers",
                    "skip_tags",
                    "start_at_task",
                    "timeout",
                    "use_fact_cache",
                    "execution_environment",
                    "host_config_key",
                    "ask_scm_branch_on_launch",
                    "ask_diff_mode_on_launch",
                    "ask_variables_on_launch",
                    "ask_limit_on_launch",
                    "ask_tags_on_launch",
                    "ask_skip_tags_on_launch",
                    "ask_job_type_on_launch",
                    "ask_verbosity_on_launch",
                    "ask_inventory_on_launch",
                    "ask_credential_on_launch",
                    "ask_execution_environment_on_launch",
                    "ask_labels_on_launch",
                    "ask_forks_on_launch",
                    "ask_job_slice_count_on_launch",
                    "ask_timeout_on_launch",
                    "ask_instance_groups_on_launch",
                    "survey_enabled",
                    "become_enabled",
                    "diff_mode",
                    "allow_simultaneous",
                    "job_slice_count",
                    "webhook_service",
                    "webhook_credential",
                    "prevent_instance_group_fallback",
                    "opa_query_path",
                ],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/controller/v2/job_templates/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/controller/v2/job_templates/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/controller/v2/job_templates/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def get_find_list_query_params(cls, ansible_data) -> Dict[str, Any]:
        """Extra query params for list find (organization scoping)."""
        org = getattr(ansible_data, "organization", None)
        if org is not None:
            return {"organization": org}
        return {}

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.job_template import AnsibleJobTemplate

        # Deserialize extra_vars JSON string back to dict
        extra_vars = api_data.get("extra_vars")
        if extra_vars and isinstance(extra_vars, str):
            try:
                extra_vars = json.loads(extra_vars)
            except (json.JSONDecodeError, ValueError):
                pass

        return AnsibleJobTemplate(
            name=api_data.get("name"),
            description=api_data.get("description"),
            job_type=api_data.get("job_type"),
            inventory=api_data.get("inventory"),
            project=api_data.get("project"),
            playbook=api_data.get("playbook"),
            scm_branch=api_data.get("scm_branch"),
            forks=api_data.get("forks"),
            limit=api_data.get("limit"),
            verbosity=api_data.get("verbosity"),
            extra_vars=extra_vars,
            job_tags=api_data.get("job_tags"),
            force_handlers=api_data.get("force_handlers"),
            skip_tags=api_data.get("skip_tags"),
            start_at_task=api_data.get("start_at_task"),
            timeout=api_data.get("timeout"),
            use_fact_cache=api_data.get("use_fact_cache"),
            execution_environment=api_data.get("execution_environment"),
            host_config_key=api_data.get("host_config_key"),
            ask_scm_branch_on_launch=api_data.get("ask_scm_branch_on_launch"),
            ask_diff_mode_on_launch=api_data.get("ask_diff_mode_on_launch"),
            ask_variables_on_launch=api_data.get("ask_variables_on_launch"),
            ask_limit_on_launch=api_data.get("ask_limit_on_launch"),
            ask_tags_on_launch=api_data.get("ask_tags_on_launch"),
            ask_skip_tags_on_launch=api_data.get("ask_skip_tags_on_launch"),
            ask_job_type_on_launch=api_data.get("ask_job_type_on_launch"),
            ask_verbosity_on_launch=api_data.get("ask_verbosity_on_launch"),
            ask_inventory_on_launch=api_data.get("ask_inventory_on_launch"),
            ask_credential_on_launch=api_data.get("ask_credential_on_launch"),
            ask_execution_environment_on_launch=api_data.get("ask_execution_environment_on_launch"),
            ask_labels_on_launch=api_data.get("ask_labels_on_launch"),
            ask_forks_on_launch=api_data.get("ask_forks_on_launch"),
            ask_job_slice_count_on_launch=api_data.get("ask_job_slice_count_on_launch"),
            ask_timeout_on_launch=api_data.get("ask_timeout_on_launch"),
            ask_instance_groups_on_launch=api_data.get("ask_instance_groups_on_launch"),
            survey_enabled=api_data.get("survey_enabled"),
            become_enabled=api_data.get("become_enabled"),
            diff_mode=api_data.get("diff_mode"),
            allow_simultaneous=api_data.get("allow_simultaneous"),
            job_slice_count=api_data.get("job_slice_count"),
            webhook_service=api_data.get("webhook_service"),
            webhook_credential=api_data.get("webhook_credential"),
            prevent_instance_group_fallback=api_data.get("prevent_instance_group_fallback"),
            opa_query_path=api_data.get("opa_query_path"),
            id=api_data.get("id"),
            created=api_data.get("created"),
            modified=api_data.get("modified"),
            url=api_data.get("url"),
        )
