"""
API v1 RoleDefinition dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIRoleDefinition_v1(BaseTransformMixin):
    """API v1 representation of a gateway role_definition."""

    permissions: Optional[List[Any]] = None
    name: Optional[str] = None
    content_type: Optional[str] = None
    description: Optional[str] = None
    id: Optional[int] = None  # read-only
    url: Optional[str] = None  # read-only
    related: Optional[Dict[str, Any]] = None  # read-only
    summary_fields: Optional[Dict[str, Any]] = None  # read-only
    modified: Optional[str] = None  # read-only
    created: Optional[str] = None  # read-only
    managed: Optional[bool] = None  # read-only
    modified_by: Optional[int] = None  # read-only
    created_by: Optional[int] = None  # read-only


class RoleDefinitionTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for RoleDefinition API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIRoleDefinition_v1":
        api_data: Dict[str, Any] = {}

        for field in (
            "permissions",
            "content_type",
            "name",
            "description",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in ("id", "url", "related", "summary_fields", "modified", "created", "managed", "modified_by", "created_by"):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIRoleDefinition_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/gateway/v1/role_definitions/",
                method="POST",
                fields=["permissions", "content_type", "name", "description"],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/gateway/v1/role_definitions/{id}/",
                method="PATCH",
                fields=["permissions", "content_type", "name", "description"],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/gateway/v1/role_definitions/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/role_definitions/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/role_definitions/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.role_definition import AnsibleRoleDefinition

        return AnsibleRoleDefinition(
            permissions=api_data.get("permissions"),
            content_type=api_data.get("content_type"),
            name=api_data.get("name"),
            description=api_data.get("description"),
            id=api_data.get("id"),
            url=api_data.get("url"),
            related=api_data.get("related"),
            summary_fields=api_data.get("summary_fields"),
            modified=api_data.get("modified"),
            created=api_data.get("created"),
            managed=api_data.get("managed"),
            modified_by=api_data.get("modified_by"),
            created_by=api_data.get("created_by"),
        )
