"""
API v1 RoleTeamAssignment dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIRoleTeamAssignment_v1(BaseTransformMixin):
    """API v1 representation of a gateway role_team_assignment."""

    role_definition: Optional[int] = None
    object_id: Optional[str] = None
    object_ansible_id: Optional[str] = None
    team: Optional[int] = None
    team_ansible_id: Optional[str] = None
    id: Optional[int] = None  # read-only
    url: Optional[str] = None  # read-only
    related: Optional[Dict[str, Any]] = None  # read-only
    summary_fields: Optional[Dict[str, Any]] = None  # read-only
    created: Optional[str] = None  # read-only
    created_by: Optional[int] = None  # read-only
    content_type: Optional[str] = None  # read-only


class RoleTeamAssignmentTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for RoleTeamAssignment API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIRoleTeamAssignment_v1":
        api_data: Dict[str, Any] = {}

        for field in (
            "object_ansible_id",
            "role_definition",
            "team",
            "team_ansible_id",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        # Resolve object_id: prefer explicit object_id, else derive from assignment_objects
        obj_id = getattr(ansible_instance, "object_id", None)
        if obj_id is not None:
            api_data["object_id"] = obj_id
        else:
            assignment_objects = getattr(ansible_instance, "assignment_objects", None)
            if assignment_objects:
                first = assignment_objects[0]
                if isinstance(first, dict):
                    api_data["object_id"] = str(first.get("name", ""))
                else:
                    api_data["object_id"] = str(first)

        for ro in ("id", "url", "related", "summary_fields", "created", "created_by", "content_type"):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIRoleTeamAssignment_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/gateway/v1/role_team_assignments/",
                method="POST",
                fields=["object_id", "object_ansible_id", "role_definition", "team", "team_ansible_id"],
                required_for="create",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/gateway/v1/role_team_assignments/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/role_team_assignments/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/role_team_assignments/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.role_team_assignments import AnsibleRoleTeamAssignments

        return AnsibleRoleTeamAssignments(
            object_id=api_data.get("object_id"),
            object_ansible_id=api_data.get("object_ansible_id"),
            role_definition=api_data.get("role_definition"),
            team=api_data.get("team"),
            team_ansible_id=api_data.get("team_ansible_id"),
            id=api_data.get("id"),
            url=api_data.get("url"),
            related=api_data.get("related"),
            summary_fields=api_data.get("summary_fields"),
            created=api_data.get("created"),
            created_by=api_data.get("created_by"),
            content_type=api_data.get("content_type"),
        )
