"""
API v1 Route dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIRoute_v1(BaseTransformMixin):
    """API v1 representation of a gateway route."""

    name: Optional[str] = None
    http_port: Optional[int] = None
    service_cluster: Optional[int] = None
    service_port: Optional[int] = None
    is_service_https: Optional[bool] = None
    service_path: Optional[str] = None
    gateway_path: Optional[str] = None
    is_internal_route: Optional[bool] = None
    description: Optional[str] = None
    enable_gateway_auth: Optional[bool] = None
    node_tags: Optional[str] = None
    enable_mtls: Optional[bool] = None
    id: Optional[int] = None  # read-only
    url: Optional[str] = None  # read-only
    related: Optional[Dict[str, Any]] = None  # read-only
    summary_fields: Optional[Dict[str, Any]] = None  # read-only
    created: Optional[str] = None  # read-only
    created_by: Optional[int] = None  # read-only
    modified: Optional[str] = None  # read-only
    modified_by: Optional[int] = None  # read-only


class RouteTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for Route API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIRoute_v1":
        api_data: Dict[str, Any] = {}

        for field in (
            "name",
            "http_port",
            "service_cluster",
            "service_port",
            "is_service_https",
            "is_internal_route",
            "service_path",
            "gateway_path",
            "description",
            "enable_gateway_auth",
            "node_tags",
            "enable_mtls",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in ("id", "url", "related", "summary_fields", "created", "created_by", "modified", "modified_by"):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIRoute_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/gateway/v1/routes/",
                method="POST",
                fields=[
                    "name",
                    "http_port",
                    "service_cluster",
                    "service_port",
                    "is_service_https",
                    "is_internal_route",
                    "service_path",
                    "gateway_path",
                    "description",
                    "enable_gateway_auth",
                    "node_tags",
                    "enable_mtls",
                ],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/gateway/v1/routes/{id}/",
                method="PATCH",
                fields=[
                    "name",
                    "http_port",
                    "service_cluster",
                    "service_port",
                    "is_service_https",
                    "is_internal_route",
                    "service_path",
                    "gateway_path",
                    "description",
                    "enable_gateway_auth",
                    "node_tags",
                    "enable_mtls",
                ],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/gateway/v1/routes/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/routes/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/routes/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.route import AnsibleRoute

        return AnsibleRoute(
            name=api_data.get("name"),
            http_port=api_data.get("http_port"),
            service_cluster=api_data.get("service_cluster"),
            service_port=api_data.get("service_port"),
            is_service_https=api_data.get("is_service_https"),
            is_internal_route=api_data.get("is_internal_route"),
            service_path=api_data.get("service_path"),
            gateway_path=api_data.get("gateway_path"),
            description=api_data.get("description"),
            enable_gateway_auth=api_data.get("enable_gateway_auth"),
            node_tags=api_data.get("node_tags"),
            enable_mtls=api_data.get("enable_mtls"),
            id=api_data.get("id"),
            url=api_data.get("url"),
            related=api_data.get("related"),
            summary_fields=api_data.get("summary_fields"),
            created=api_data.get("created"),
            created_by=api_data.get("created_by"),
            modified=api_data.get("modified"),
            modified_by=api_data.get("modified_by"),
        )
