"""
API v1 ServiceKey dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIServiceKey_v1(BaseTransformMixin):
    """API v1 representation of a gateway service_key."""

    service_cluster: Optional[int] = None
    mark_previous_inactive: Optional[bool] = None
    name: Optional[str] = None
    is_active: Optional[bool] = None
    algorithm: Optional[str] = None
    secret_length: Optional[int] = None
    id: Optional[int] = None  # read-only
    url: Optional[str] = None  # read-only
    related: Optional[Dict[str, Any]] = None  # read-only
    summary_fields: Optional[Dict[str, Any]] = None  # read-only
    created: Optional[str] = None  # read-only
    created_by: Optional[int] = None  # read-only
    modified: Optional[str] = None  # read-only
    modified_by: Optional[int] = None  # read-only
    secret: Optional[str] = None  # read-only


class ServiceKeyTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for ServiceKey API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIServiceKey_v1":
        api_data: Dict[str, Any] = {}

        for field in (
            "name",
            "service_cluster",
            "is_active",
            "algorithm",
            "secret_length",
            "mark_previous_inactive",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in ("id", "url", "related", "summary_fields", "created", "created_by", "modified", "modified_by", "secret"):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIServiceKey_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/gateway/v1/service_keys/",
                method="POST",
                fields=["name", "service_cluster", "is_active", "algorithm", "secret_length", "mark_previous_inactive"],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/gateway/v1/service_keys/{id}/",
                method="PATCH",
                fields=["name", "service_cluster", "is_active", "algorithm", "secret_length", "mark_previous_inactive"],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/gateway/v1/service_keys/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/service_keys/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/service_keys/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.service_key import AnsibleServiceKey

        return AnsibleServiceKey(
            name=api_data.get("name"),
            service_cluster=api_data.get("service_cluster"),
            is_active=api_data.get("is_active"),
            algorithm=api_data.get("algorithm"),
            secret_length=api_data.get("secret_length"),
            mark_previous_inactive=api_data.get("mark_previous_inactive"),
            id=api_data.get("id"),
            url=api_data.get("url"),
            related=api_data.get("related"),
            summary_fields=api_data.get("summary_fields"),
            created=api_data.get("created"),
            created_by=api_data.get("created_by"),
            modified=api_data.get("modified"),
            modified_by=api_data.get("modified_by"),
            secret=api_data.get("secret"),
        )
