"""
API v1 ServiceCluster dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIServiceCluster_v1(BaseTransformMixin):
    """API v1 representation of a gateway service_cluster."""

    name: Optional[str] = None
    service_type: Optional[int] = None
    auth_type: Optional[str] = None
    upstream_hostname: Optional[str] = None
    dns_discovery_type: Optional[str] = None
    dns_lookup_family: Optional[str] = None
    outlier_detection_enabled: Optional[bool] = None
    outlier_detection_consecutive_5xx: Optional[int] = None
    outlier_detection_interval_seconds: Optional[int] = None
    outlier_detection_base_ejection_time_seconds: Optional[int] = None
    outlier_detection_max_ejection_percent: Optional[int] = None
    health_checks_enabled: Optional[bool] = None
    health_check_timeout_seconds: Optional[int] = None
    health_check_interval_seconds: Optional[int] = None
    health_check_unhealthy_threshold: Optional[int] = None
    health_check_healthy_threshold: Optional[int] = None
    healthy_panic_threshold: Optional[int] = None
    id: Optional[int] = None  # read-only
    url: Optional[str] = None  # read-only
    related: Optional[Dict[str, Any]] = None  # read-only
    summary_fields: Optional[Dict[str, Any]] = None  # read-only
    created: Optional[str] = None  # read-only
    created_by: Optional[int] = None  # read-only
    modified: Optional[str] = None  # read-only
    modified_by: Optional[int] = None  # read-only
    service_id: Optional[str] = None  # read-only


class ServiceClusterTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for ServiceCluster API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIServiceCluster_v1":
        api_data: Dict[str, Any] = {}

        for field in (
            "name",
            "service_type",
            "auth_type",
            "upstream_hostname",
            "dns_discovery_type",
            "dns_lookup_family",
            "outlier_detection_enabled",
            "outlier_detection_consecutive_5xx",
            "outlier_detection_interval_seconds",
            "outlier_detection_base_ejection_time_seconds",
            "outlier_detection_max_ejection_percent",
            "health_checks_enabled",
            "health_check_timeout_seconds",
            "health_check_interval_seconds",
            "health_check_unhealthy_threshold",
            "health_check_healthy_threshold",
            "healthy_panic_threshold",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in ("id", "url", "related", "summary_fields", "created", "created_by", "modified", "modified_by", "service_id"):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIServiceCluster_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/gateway/v1/service_clusters/",
                method="POST",
                fields=[
                    "name",
                    "service_type",
                    "auth_type",
                    "upstream_hostname",
                    "dns_discovery_type",
                    "dns_lookup_family",
                    "outlier_detection_enabled",
                    "outlier_detection_consecutive_5xx",
                    "outlier_detection_interval_seconds",
                    "outlier_detection_base_ejection_time_seconds",
                    "outlier_detection_max_ejection_percent",
                    "health_checks_enabled",
                    "health_check_timeout_seconds",
                    "health_check_interval_seconds",
                    "health_check_unhealthy_threshold",
                    "health_check_healthy_threshold",
                    "healthy_panic_threshold",
                ],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/gateway/v1/service_clusters/{id}/",
                method="PATCH",
                fields=[
                    "name",
                    "service_type",
                    "auth_type",
                    "upstream_hostname",
                    "dns_discovery_type",
                    "dns_lookup_family",
                    "outlier_detection_enabled",
                    "outlier_detection_consecutive_5xx",
                    "outlier_detection_interval_seconds",
                    "outlier_detection_base_ejection_time_seconds",
                    "outlier_detection_max_ejection_percent",
                    "health_checks_enabled",
                    "health_check_timeout_seconds",
                    "health_check_interval_seconds",
                    "health_check_unhealthy_threshold",
                    "health_check_healthy_threshold",
                    "healthy_panic_threshold",
                ],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/gateway/v1/service_clusters/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/service_clusters/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/service_clusters/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.service_cluster import AnsibleServiceCluster

        return AnsibleServiceCluster(
            name=api_data.get("name"),
            service_type=api_data.get("service_type"),
            auth_type=api_data.get("auth_type"),
            upstream_hostname=api_data.get("upstream_hostname"),
            dns_discovery_type=api_data.get("dns_discovery_type"),
            dns_lookup_family=api_data.get("dns_lookup_family"),
            outlier_detection_enabled=api_data.get("outlier_detection_enabled"),
            outlier_detection_consecutive_5xx=api_data.get("outlier_detection_consecutive_5xx"),
            outlier_detection_interval_seconds=api_data.get("outlier_detection_interval_seconds"),
            outlier_detection_base_ejection_time_seconds=api_data.get("outlier_detection_base_ejection_time_seconds"),
            outlier_detection_max_ejection_percent=api_data.get("outlier_detection_max_ejection_percent"),
            health_checks_enabled=api_data.get("health_checks_enabled"),
            health_check_timeout_seconds=api_data.get("health_check_timeout_seconds"),
            health_check_interval_seconds=api_data.get("health_check_interval_seconds"),
            health_check_unhealthy_threshold=api_data.get("health_check_unhealthy_threshold"),
            health_check_healthy_threshold=api_data.get("health_check_healthy_threshold"),
            healthy_panic_threshold=api_data.get("healthy_panic_threshold"),
            id=api_data.get("id"),
            url=api_data.get("url"),
            related=api_data.get("related"),
            summary_fields=api_data.get("summary_fields"),
            created=api_data.get("created"),
            created_by=api_data.get("created_by"),
            modified=api_data.get("modified"),
            modified_by=api_data.get("modified_by"),
            service_id=api_data.get("service_id"),
        )
