"""
API v1 Setting dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APISetting_v1(BaseTransformMixin):
    """API v1 representation of a gateway setting."""

    settings: Optional[Dict[str, Any]] = None  # flat {key: value} dict


class SettingTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for Setting API v1."""

    # Settings is a singleton resource — no canonical or system key
    is_singleton = True

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APISetting_v1":
        api_data: Dict[str, Any] = {}

        settings_val = getattr(ansible_instance, "settings", None)
        if settings_val is not None:
            api_data["settings"] = settings_val

        return APISetting_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "update": EndpointOperation(
                path="/api/gateway/v1/settings/",
                method="PATCH",
                fields=["settings"],
                required_for="update",
                flatten_body=True,
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/settings/all/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/settings/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.settings import AnsibleSettings

        # api_data may be a flat settings dict {KEY: value, ...}
        # or a list item {key: KEY, value: val} — handle both
        if isinstance(api_data, dict) and not any(k in api_data for k in ("key", "value", "id", "url")):
            # Flat dict from /settings/all/ endpoint
            return AnsibleSettings(settings=dict(api_data))

        # Fall back: return empty
        return AnsibleSettings()


# Alias: the loader looks for SettingsTransformMixin_v1 (plural)
SettingsTransformMixin_v1 = SettingTransformMixin_v1
