"""
API v1 Token dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIToken_v1(BaseTransformMixin):
    """API v1 representation of a gateway token."""

    application: Optional[int] = None
    description: Optional[str] = None
    scope: Optional[str] = None
    id: Optional[int] = None  # read-only
    url: Optional[str] = None  # read-only
    related: Optional[Dict[str, Any]] = None  # read-only
    summary_fields: Optional[Dict[str, Any]] = None  # read-only
    created: Optional[str] = None  # read-only
    created_by: Optional[int] = None  # read-only
    modified: Optional[str] = None  # read-only
    modified_by: Optional[int] = None  # read-only
    expires: Optional[str] = None  # read-only
    user: Optional[int] = None  # read-only
    last_used: Optional[str] = None  # read-only
    token: Optional[str] = None  # read-only
    refresh_token: Optional[str] = None  # read-only


class TokenTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for Token API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIToken_v1":
        api_data: Dict[str, Any] = {}

        for field in (
            "application",
            "description",
            "scope",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in (
            "id",
            "url",
            "related",
            "summary_fields",
            "created",
            "created_by",
            "modified",
            "modified_by",
            "expires",
            "user",
            "last_used",
            "token",
            "refresh_token",
        ):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIToken_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/gateway/v1/tokens/",
                method="POST",
                fields=["application", "description", "scope"],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/gateway/v1/tokens/{id}/",
                method="PATCH",
                fields=["application", "description", "scope"],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/gateway/v1/tokens/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/tokens/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/tokens/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "name"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.token import AnsibleToken

        return AnsibleToken(
            application=api_data.get("application"),
            description=api_data.get("description"),
            scope=api_data.get("scope"),
            id=api_data.get("id"),
            url=api_data.get("url"),
            related=api_data.get("related"),
            summary_fields=api_data.get("summary_fields"),
            created=api_data.get("created"),
            created_by=api_data.get("created_by"),
            modified=api_data.get("modified"),
            modified_by=api_data.get("modified_by"),
            expires=api_data.get("expires"),
            user=api_data.get("user"),
            last_used=api_data.get("last_used"),
            token=api_data.get("token"),
            refresh_token=api_data.get("refresh_token"),
        )
