"""
API v1 User dataclass and transform mixin.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
Review and customise before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Union

from ...platform.base_transform import BaseTransformMixin
from ...platform.types import EndpointOperation, TransformContext


@dataclass
class APIUser_v1(BaseTransformMixin):
    """API v1 representation of a gateway user."""

    username: Optional[str] = None
    email: Optional[str] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    password: Optional[str] = None
    is_superuser: Optional[bool] = None
    authenticators: Optional[List[Any]] = None
    authenticator_uid: Optional[str] = None
    associated_authenticators: Optional[Any] = None
    id: Optional[int] = None  # read-only
    url: Optional[str] = None  # read-only
    related: Optional[Dict[str, Any]] = None  # read-only
    summary_fields: Optional[Dict[str, Any]] = None  # read-only
    created: Optional[str] = None  # read-only
    created_by: Optional[int] = None  # read-only
    modified: Optional[str] = None  # read-only
    modified_by: Optional[int] = None  # read-only
    last_login: Optional[str] = None  # read-only
    last_login_from: Optional[str] = None  # read-only
    is_platform_auditor: Optional[bool] = None  # read-only
    managed: Optional[bool] = None  # read-only


class UserTransformMixin_v1(BaseTransformMixin):
    """Transform mixin for User API v1."""

    @classmethod
    def from_ansible_data(
        cls,
        ansible_instance,
        context: Union[TransformContext, Dict[str, Any]],
    ) -> "APIUser_v1":
        api_data: Dict[str, Any] = {}

        for field in (
            "username",
            "email",
            "first_name",
            "last_name",
            "password",
            "is_superuser",
            "authenticators",
            "authenticator_uid",
            "associated_authenticators",
        ):
            val = getattr(ansible_instance, field, None)
            if val is not None:
                api_data[field] = val

        for ro in (
            "id",
            "url",
            "related",
            "summary_fields",
            "created",
            "created_by",
            "modified",
            "modified_by",
            "last_login",
            "last_login_from",
            "is_platform_auditor",
            "managed",
        ):
            val = getattr(ansible_instance, ro, None)
            if val is not None:
                api_data[ro] = val

        return APIUser_v1(**api_data)

    @classmethod
    def get_endpoint_operations(cls) -> Dict[str, EndpointOperation]:
        return {
            "create": EndpointOperation(
                path="/api/gateway/v1/users/",
                method="POST",
                fields=[
                    "username",
                    "email",
                    "first_name",
                    "last_name",
                    "password",
                    "is_superuser",
                    "authenticators",
                    "authenticator_uid",
                    "associated_authenticators",
                ],
                required_for="create",
                order=1,
            ),
            "update": EndpointOperation(
                path="/api/gateway/v1/users/{id}/",
                method="PATCH",
                fields=[
                    "username",
                    "email",
                    "first_name",
                    "last_name",
                    "password",
                    "is_superuser",
                    "authenticators",
                    "authenticator_uid",
                    "associated_authenticators",
                ],
                path_params=["id"],
                required_for="update",
                order=1,
            ),
            "delete": EndpointOperation(
                path="/api/gateway/v1/users/{id}/",
                method="DELETE",
                fields=[],
                path_params=["id"],
                required_for="delete",
                order=1,
            ),
            "get": EndpointOperation(
                path="/api/gateway/v1/users/{id}/",
                method="GET",
                fields=[],
                path_params=["id"],
                required_for="find",
                order=1,
            ),
            "list": EndpointOperation(
                path="/api/gateway/v1/users/",
                method="GET",
                fields=[],
                required_for="find",
                order=1,
            ),
        }

    @classmethod
    def get_lookup_field(cls) -> str:
        return "username"

    @classmethod
    def from_api(
        cls,
        api_data: Dict[str, Any],
        context: Union[TransformContext, Dict[str, Any]],
    ):
        from ...ansible_models.users import AnsibleUsers

        return AnsibleUsers(
            username=api_data.get("username"),
            email=api_data.get("email"),
            first_name=api_data.get("first_name"),
            last_name=api_data.get("last_name"),
            password=api_data.get("password"),
            is_superuser=api_data.get("is_superuser"),
            authenticators=api_data.get("authenticators"),
            authenticator_uid=api_data.get("authenticator_uid"),
            associated_authenticators=api_data.get("associated_authenticators"),
            id=api_data.get("id"),
            url=api_data.get("url"),
            related=api_data.get("related"),
            summary_fields=api_data.get("summary_fields"),
            created=api_data.get("created"),
            created_by=api_data.get("created_by"),
            modified=api_data.get("modified"),
            modified_by=api_data.get("modified_by"),
            last_login=api_data.get("last_login"),
            last_login_from=api_data.get("last_login_from"),
            is_platform_auditor=api_data.get("is_platform_auditor"),
            managed=api_data.get("managed"),
        )
