---
- name: "Prepare — service_key (replaced)"
  hosts: localhost
  gather_facts: false
  vars_files:
  - vars.yml
  tasks:
  - name: Seed service_key to be replaced (prerequisite for replaced)
    ansible.platform.service_key:
      config:
      - "{{ prepare_config }}"
      state: merged
      gateway_hostname: "{{ gateway_hostname }}"
      gateway_username: "{{ gateway_username }}"
      gateway_password: "{{ gateway_password }}"
      gateway_validate_certs: "{{ gateway_validate_certs }}"

