---
- name: "Prepare — role_definition (gathered)"
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: Seed role_definition to be gathered (prerequisite for gathered)
      ansible.platform.role_definition:
        config:
          - "{{ prepare_config }}"
        state: merged
        gateway_hostname: "{{ gateway_hostname }}"
        gateway_username: "{{ gateway_username }}"
        gateway_password: "{{ gateway_password }}"
        gateway_validate_certs: "{{ gateway_validate_certs }}"

...
