---
- name: "Converge — service_type (merged)"
  hosts: localhost
  gather_facts: false
  vars_files:
  - vars.yml
  tasks:
  - name: Run ansible.platform.service_type with state=merged
    ansible.platform.service_type:
      config:
      - "{{ expected_config }}"
      state: merged
      gateway_hostname: "{{ gateway_hostname }}"
      gateway_username: "{{ gateway_username }}"
      gateway_password: "{{ gateway_password }}"
      gateway_validate_certs: "{{ gateway_validate_certs }}"
    register: result

