"""
Ansible Application dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleApplications(BaseTransformMixin):
    """Ansible representation of a gateway application (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "application"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    name: Optional[str] = None
    organization: Optional[int] = None
    client_type: Optional[str] = None
    authorization_grant_type: Optional[str] = None
    redirect_uris: Optional[str] = None
    post_logout_redirect_uris: Optional[str] = None
    algorithm: Optional[str] = None
    user: Optional[int] = None
    description: Optional[str] = None
    app_url: Optional[str] = None
    skip_authorization: Optional[bool] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    modified: Optional[str] = None
    modified_by: Optional[int] = None
    client_id: Optional[str] = None
    client_secret: Optional[str] = None
