"""
Ansible AuthenticatorUser dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleAuthenticatorUsers(BaseTransformMixin):
    """Ansible representation of a gateway authenticator_user (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "authenticator_user"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = False
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    # Read-only fields (populated from API)
