"""
Ansible AuthenticatorMap dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleAuthenticatorMap(BaseTransformMixin):
    """Ansible representation of a gateway authenticator_map (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "authenticator_map"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    name: Optional[str] = None
    authenticator: Optional[int] = None
    triggers: Optional[Any] = None
    map_type: Optional[str] = None
    role: Optional[str] = None
    organization: Optional[str] = None
    team: Optional[str] = None
    revoke: Optional[bool] = None
    order: Optional[int] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    modified: Optional[str] = None
    modified_by: Optional[int] = None
