"""
Ansible Authenticator dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleAuthenticator(BaseTransformMixin):
    """Ansible representation of a gateway authenticator (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "authenticator"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    name: Optional[str] = None
    configuration: Optional[Any] = None
    type: Optional[str] = None
    enabled: Optional[bool] = None
    create_objects: Optional[bool] = None
    remove_users: Optional[bool] = None
    order: Optional[int] = None
    slug: Optional[str] = None
    auto_migrate_users_to: Optional[int] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    modified: Optional[str] = None
    modified_by: Optional[int] = None
