"""
Ansible FeatureFlag dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleFeatureFlag(BaseTransformMixin):
    """Ansible representation of a gateway feature_flag (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "feature_flag"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = False
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    name: Optional[str] = None
    value: Optional[str] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    toggle_type: Optional[str] = None
    condition: Optional[str] = None
    description: Optional[str] = None
    required: Optional[bool] = None
    support_level: Optional[str] = None
    visibility: Optional[bool] = None
    labels: Optional[List[Any]] = None
