"""
Ansible RoleTeamAssignment dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleRoleTeamAssignments(BaseTransformMixin):
    """Ansible representation of a gateway role_team_assignment (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "role_team_assignment"
    CANONICAL_KEY = None  # Category C: no canonical key, match by content
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})
    INPUT_ONLY_FIELDS = frozenset({"assignment_objects"})  # transformed to object_id, never returned by API

    role_definition: Optional[Any] = None  # int ID or str name (resolved in transform)
    object_id: Optional[str] = None
    object_ansible_id: Optional[str] = None
    team: Optional[Any] = None  # int ID or str name (resolved in transform)
    team_ansible_id: Optional[str] = None
    assignment_objects: Optional[List[Any]] = None  # input-only: [{name, type}] → object_id

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    content_type: Optional[str] = None
