"""
Ansible RoleDefinition dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleRoleDefinitions(BaseTransformMixin):
    """Ansible representation of a gateway role_definition (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "role_definition"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    permissions: Optional[List[Any]] = None
    name: Optional[str] = None
    content_type: Optional[str] = None
    description: Optional[str] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    modified: Optional[str] = None
    created: Optional[str] = None
    managed: Optional[bool] = None
    modified_by: Optional[int] = None
    created_by: Optional[int] = None
