"""
Ansible ServiceKey dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleServiceKey(BaseTransformMixin):
    """Ansible representation of a gateway service_key (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "service_key"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    service_cluster: Optional[int] = None
    mark_previous_inactive: Optional[bool] = None
    name: Optional[str] = None
    is_active: Optional[bool] = None
    algorithm: Optional[str] = None
    secret_length: Optional[int] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    modified: Optional[str] = None
    modified_by: Optional[int] = None
    secret: Optional[str] = None
