"""
Ansible ServiceCluster dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleServiceCluster(BaseTransformMixin):
    """Ansible representation of a gateway service_cluster (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "service_cluster"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    name: Optional[str] = None
    service_type: Optional[int] = None
    auth_type: Optional[str] = None
    upstream_hostname: Optional[str] = None
    dns_discovery_type: Optional[str] = None
    dns_lookup_family: Optional[str] = None
    outlier_detection_enabled: Optional[bool] = None
    outlier_detection_consecutive_5xx: Optional[int] = None
    outlier_detection_interval_seconds: Optional[int] = None
    outlier_detection_base_ejection_time_seconds: Optional[int] = None
    outlier_detection_max_ejection_percent: Optional[int] = None
    health_checks_enabled: Optional[bool] = None
    health_check_timeout_seconds: Optional[int] = None
    health_check_interval_seconds: Optional[int] = None
    health_check_unhealthy_threshold: Optional[int] = None
    health_check_healthy_threshold: Optional[int] = None
    healthy_panic_threshold: Optional[int] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    modified: Optional[str] = None
    modified_by: Optional[int] = None
    service_id: Optional[str] = None
