"""
Ansible Setting dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleSetting(BaseTransformMixin):
    """Ansible representation of a gateway setting (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "settings"
    CANONICAL_KEY = None  # Singleton resource — no canonical key
    SYSTEM_KEY = None     # Singleton resource — no system key
    SUPPORTS_DELETE = False
    VALID_STATES = frozenset({"merged", "gathered"})

    # Settings payload: {KEY: value, ...}
    settings: Optional[Dict[str, Any]] = None
