"""
Ansible Token dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleToken(BaseTransformMixin):
    """Ansible representation of a gateway token (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "token"
    CANONICAL_KEY = "description"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    application: Optional[int] = None
    description: Optional[str] = None
    scope: Optional[str] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    modified: Optional[str] = None
    modified_by: Optional[int] = None
    expires: Optional[str] = None
    user: Optional[int] = None
    last_used: Optional[str] = None
    token: Optional[str] = None
    refresh_token: Optional[str] = None
