"""
Ansible UiPluginRoute dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleUiPluginRoutes(BaseTransformMixin):
    """Ansible representation of a gateway ui_plugin_route (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "ui_plugin_route"
    CANONICAL_KEY = "name"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    name: Optional[str] = None
    http_port: Optional[int] = None
    service_cluster: Optional[int] = None
    service_port: Optional[int] = None
    is_service_https: Optional[bool] = None
    ui_plugin_path: Optional[str] = None
    description: Optional[str] = None
    order: Optional[int] = None
    node_tags: Optional[str] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    modified: Optional[str] = None
    modified_by: Optional[int] = None
    gateway_path: Optional[str] = None
