"""
Ansible User dataclass — user-facing stable interface.

Auto-generated by tools/generate_resource.py from the Gateway OpenAPI spec.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from ..platform.base_transform import BaseTransformMixin


@dataclass
class AnsibleUsers(BaseTransformMixin):
    """Ansible representation of a gateway user (resource module pattern)."""

    # Resource metadata for the base action plugin
    MODULE_NAME = "user"
    CANONICAL_KEY = "username"
    SYSTEM_KEY = "id"
    SUPPORTS_DELETE = True
    VALID_STATES = frozenset({"merged", "replaced", "overridden", "deleted", "gathered"})

    username: Optional[str] = None
    email: Optional[str] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    password: Optional[str] = None
    is_superuser: Optional[bool] = None
    authenticators: Optional[List[Any]] = None
    authenticator_uid: Optional[str] = None
    associated_authenticators: Optional[Any] = None

    # Read-only fields (populated from API)
    id: Optional[int] = None
    url: Optional[str] = None
    related: Optional[Dict[str, Any]] = None
    summary_fields: Optional[Dict[str, Any]] = None
    created: Optional[str] = None
    created_by: Optional[int] = None
    modified: Optional[str] = None
    modified_by: Optional[int] = None
    last_login: Optional[str] = None
    last_login_from: Optional[str] = None
    is_platform_auditor: Optional[bool] = None
    managed: Optional[bool] = None
