---
- name: "Prepare — service_type (gathered)"
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: Seed service_type to be gathered (prerequisite for gathered)
      ansible.platform.service_type:
        config:
          - "{{ prepare_config }}"
        state: merged
        gateway_hostname: "{{ gateway_hostname }}"
        gateway_username: "{{ gateway_username }}"
        gateway_password: "{{ gateway_password }}"
        gateway_validate_certs: "{{ gateway_validate_certs }}"

...
