---
- name: Ensure that AAP Gateway is up and running
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set AAP Gateway vars
      ansible.builtin.set_fact:
        gateway_hostname: https://localhost:8000
        gateway_username: admin
        gateway_password: admin
        gateway_validate_certs: false
        gateway_request_timeout: 60

    - name: Validate server is up with a URI call
      ansible.builtin.uri:
        url: "{{ gateway_hostname }}/api/gateway/v1/settings/"
        force_basic_auth: true
        url_username: "{{ gateway_username }}"
        url_password: "{{ gateway_password }}"
        validate_certs: "{{ gateway_validate_certs }}"
      register: server_ping
      until: server_ping is not failed
      retries: 30
      delay: 2
...
