#!/usr/bin/env python
# -*- coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Action plugin for ansible.platform.ui_plugin_routes resource module.

Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ansible_collections.ansible.platform.plugins.action.base_action import (
    BaseResourceActionPlugin,
)


class ActionModule(BaseResourceActionPlugin):
    """Resource module action plugin for ui_plugin_routes."""

    USER_MODEL = "plugins.plugin_utils.ansible_models.ui_plugin_routes.AnsibleUiPluginRoutes"
