#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: application
short_description: Manage gateway application resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway application resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of application resource configurations.
        - Each entry represents a desired application state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        organization:
          required: true
          type: int
          description: Organization containing this application.
        client_type:
          required: true
          type: str
          description:
            - Set to Public or Confidential depending on how secure the client device is.
            - "confidential - Confidential"
            - "public - Public"
        authorization_grant_type:
          required: true
          type: str
          description:
            - The Grant type the user must use for acquire tokens for this application.
            - "authorization-code - Authorization code"
            - "password - Resource owner password-based"
        redirect_uris:
          type: str
          description: Allowed URIs list, space separated
        post_logout_redirect_uris:
          type: str
          description: Allowed Post Logout URIs list, space separated
        algorithm:
          type: str
          description:
            - "empty string - No OIDC support"
            - "RS256 - RSA with SHA-2 256"
            - "HS256 - HMAC with SHA-2 256"
        user:
          type: int
          description: The user who created the application.
        description:
          type: str
          description: A description of this application.
        app_url:
          type: str
          description: The URL of this application.
        skip_authorization:
          type: bool
          description: Set True to skip authorization step for completely trusted applications.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create application resources (merged)
  ansible.platform.application:
    config:
      - name: "my-application"
    state: merged

- name: Gather current application state
  ansible.platform.application:
    state: gathered
  register: result

- name: Delete specific application resources
  ansible.platform.application:
    config:
      - name: "my-application"
    state: deleted

- name: Override — ensure only these application resources exist
  ansible.platform.application:
    config:
      - name: "keep-this-application"
    state: overridden
"""

RETURN = """
before:
  description: The state of the application resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the application resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered application resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
