#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: authenticator_map
short_description: Manage gateway authenticator_map resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway authenticator_map resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of authenticator_map resource configurations.
        - Each entry represents a desired authenticator_map state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        authenticator:
          required: true
          type: int
          description: The authenticator this mapping belongs to.
        triggers:
          required: true
          type: str
          description: >-
            Required. Trigger conditions dictionary that determines when this map applies.
            See /trigger_definition/ for structure details. Only one top-level key per request.
        map_type:
          type: str
          description:
            - What will the map grant the user? System access (allow) a team or organization membership, the superuser flag or a role in the system.
            - '`allow` - allow'
            - '`is_superuser` - is_superuser'
            - '`role` - role'
            - '`organization` - organization'
            - '`team` - team'

        role:
          type: str
          description: The role this map will grant the authenticating user to the targeted object. Will expand {% for_attr_value(user_orgs) %} syntax
        organization:
          type: str
          description: An organization name this rule works on. Will expand {% for_attr_value(user_orgs) %} syntax
        team:
          type: str
          description: A team name this rule works on. Will expand {% for_attr_value(user_orgs) %} syntax.
        revoke:
          type: bool
          description: Revoke the permission if a user does not meet this rule.
        order:
          type: int
          description: >-
            The order in which this rule should be processed, smaller numbers are of higher precedence.
            Items with the same order will be executed in random order.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create authenticator_map resources (merged)
  ansible.platform.authenticator_map:
    config:
      - name: "my-authenticator_map"
    state: merged

- name: Gather current authenticator_map state
  ansible.platform.authenticator_map:
    state: gathered
  register: result

- name: Delete specific authenticator_map resources
  ansible.platform.authenticator_map:
    config:
      - name: "my-authenticator_map"
    state: deleted

- name: Override — ensure only these authenticator_map resources exist
  ansible.platform.authenticator_map:
    config:
      - name: "keep-this-authenticator_map"
    state: overridden
"""

RETURN = """
before:
  description: The state of the authenticator_map resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the authenticator_map resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered authenticator_map resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
