#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: authenticators
short_description: Manage gateway authenticator resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway authenticator resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of authenticator resource configurations.
        - Each entry represents a desired authenticator state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        configuration:
          required: true
          type: str
          description: The required configuration for this source.
        type:
          required: true
          type: str
          description:
            - "ansible_base.authentication.authenticator_plugins.github_org"
            - >-
              `ansible_base.authentication.authenticator_plugins.github_enterprise_org`
              - ansible_base.authentication.authenticator_plugins.github_enterprise_org
            - '`ansible_base.authentication.authenticator_plugins.saml` - ansible_base.authentication.authenticator_plugins.saml'
            - '`ansible_base.authentication.authenticator_plugins.local` - ansible_base.authentication.authenticator_plugins.local'
            - '`ansible_base.authentication.authenticator_plugins.ldap` - ansible_base.authentication.authenticator_plugins.ldap'
            - '`ansible_base.authentication.authenticator_plugins.google_oauth2` - ansible_base.authentication.authenticator_plugins.google_oauth2'
            - '`ansible_base.authentication.authenticator_plugins.radius` - ansible_base.authentication.authenticator_plugins.radius'
            - '`ansible_base.authentication.authenticator_plugins.github` - ansible_base.authentication.authenticator_plugins.github'
            - '`ansible_base.authentication.authenticator_plugins.oidc` - ansible_base.authentication.authenticator_plugins.oidc'
            - >-
              `ansible_base.authentication.authenticator_plugins.github_enterprise_team`
              - ansible_base.authentication.authenticator_plugins.github_enterprise_team
            - '`ansible_base.authentication.authenticator_plugins.github_enterprise` - ansible_base.authentication.authenticator_plugins.github_enterprise'
            - '`ansible_base.authentication.authenticator_plugins.keycloak` - ansible_base.authentication.authenticator_plugins.keycloak'
            - '`ansible_base.authentication.authenticator_plugins.azuread` - ansible_base.authentication.authenticator_plugins.azuread'
            - '`ansible_base.authentication.authenticator_plugins.github_team` - ansible_base.authentication.authenticator_plugins.github_team'
            - '`ansible_base.authentication.authenticator_plugins.tacacs` - ansible_base.authentication.authenticator_plugins.tacacs'
        enabled:
          type: bool
          description: Should this authenticator be enabled.
        create_objects:
          type: bool
          description: Allow authenticator to create objects (users, teams, organizations).
        remove_users:
          type: bool
          description: When a user authenticates from this source should they be removed from any other groups they were previously added to.
        order:
          type: int
          description: The order in which an authenticator will be tried. This only pertains to username/password authenticators.
        slug:
          type: str
          description: An immutable identifier for the authenticator; used to generate the sso uri for sso authenticator types
        auto_migrate_users_to:
          type: int
          description: >-
            Automatically move users from this authenticator to the target authenticator
            when a matching user logs in via the target authenticator. For this to work,
            the field used for the user ID on both authenticators needs to have the same
            value. This should only be used when migrating users between two authentication
            mechanisms that share the same user database (such as when both IDPs share
            the same LDAP user directory).
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create authenticator resources (merged)
  ansible.platform.authenticators:
    config:
      - name: "my-authenticator"
    state: merged

- name: Gather current authenticator state
  ansible.platform.authenticators:
    state: gathered
  register: result

- name: Delete specific authenticator resources
  ansible.platform.authenticators:
    config:
      - name: "my-authenticator"
    state: deleted

- name: Override — ensure only these authenticator resources exist
  ansible.platform.authenticators:
    config:
      - name: "keep-this-authenticator"
    state: overridden
...
"""

RETURN = """
before:
  description: The state of the authenticator resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the authenticator resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered authenticator resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
