#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: authenticator_users
short_description: Manage gateway authenticator_user resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway authenticator_user resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of authenticator_user resource configurations.
        - Each entry represents a desired authenticator_user state.
      type: list
      elements: dict
      suboptions:
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create authenticator_user resources (merged)
  ansible.platform.authenticator_users:
    config:
      - name: "my-authenticator_user"
    state: merged

- name: Gather current authenticator_user state
  ansible.platform.authenticator_users:
    state: gathered
  register: result

- name: Delete specific authenticator_user resources
  ansible.platform.authenticator_users:
    config:
      - name: "my-authenticator_user"
    state: deleted

- name: Override — ensure only these authenticator_user resources exist
  ansible.platform.authenticator_users:
    config:
      - name: "keep-this-authenticator_user"
    state: overridden
...
"""

RETURN = """
before:
  description: The state of the authenticator_user resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the authenticator_user resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered authenticator_user resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
