#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: ca_certificates
short_description: Manage gateway ca_certificate resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway ca_certificate resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of ca_certificate resource configurations.
        - Each entry represents a desired ca_certificate state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        pem_data:
          required: true
          type: str
          description: The pem_data of the CaCertificate.
        sha256:
          required: true
          type: str
          description: The sha256 of the CaCertificate.
        related_id_reference:
          type: str
          description: Reference to an object that is related to this CA.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create ca_certificate resources (merged)
  ansible.platform.ca_certificates:
    config:
      - name: "my-ca_certificate"
    state: merged

- name: Gather current ca_certificate state
  ansible.platform.ca_certificates:
    state: gathered
  register: result

- name: Delete specific ca_certificate resources
  ansible.platform.ca_certificates:
    config:
      - name: "my-ca_certificate"
    state: deleted

- name: Override — ensure only these ca_certificate resources exist
  ansible.platform.ca_certificates:
    config:
      - name: "keep-this-ca_certificate"
    state: overridden
...
"""

RETURN = """
before:
  description: The state of the ca_certificate resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the ca_certificate resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered ca_certificate resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
