#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: feature_flag
short_description: Manage gateway feature_flag resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway feature_flag resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of feature_flag resource configurations.
        - Each entry represents a desired feature_flag state.
      type: list
      elements: dict
      suboptions:
        name:
          type: str
          description: The name (identifier) of the feature flag.
        value:
          type: str
          description: The value used to evaluate the conditional specified.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create feature_flag resources (merged)
  ansible.platform.feature_flag:
    config:
      - name: "my-feature_flag"
    state: merged

- name: Gather current feature_flag state
  ansible.platform.feature_flag:
    state: gathered
  register: result

- name: Delete specific feature_flag resources
  ansible.platform.feature_flag:
    config:
      - name: "my-feature_flag"
    state: deleted

- name: Override — ensure only these feature_flag resources exist
  ansible.platform.feature_flag:
    config:
      - name: "keep-this-feature_flag"
    state: overridden
"""

RETURN = """
before:
  description: The state of the feature_flag resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the feature_flag resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered feature_flag resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
