#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: http_port
short_description: Manage gateway http_port resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway http_port resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of http_port resource configurations.
        - Each entry represents a desired http_port state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        number:
          required: true
          type: int
          description: The port number to listen on.
        use_https:
          type: bool
          description: Secure this port with HTTPS.
        is_api_port:
          type: bool
          description: If true, this port will be used to serve the AAP service APIs. Only one port can be the API port.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create http_port resources (merged)
  ansible.platform.http_port:
    config:
      - name: "my-http_port"
    state: merged

- name: Gather current http_port state
  ansible.platform.http_port:
    state: gathered
  register: result

- name: Delete specific http_port resources
  ansible.platform.http_port:
    config:
      - name: "my-http_port"
    state: deleted

- name: Override — ensure only these http_port resources exist
  ansible.platform.http_port:
    config:
      - name: "keep-this-http_port"
    state: overridden
"""

RETURN = """
before:
  description: The state of the http_port resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the http_port resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered http_port resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
