#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: organization
short_description: Manage gateway organization resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway organization resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of organization resource configurations.
        - Each entry represents a desired organization state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        description:
          type: str
          description: The organization description.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create organization resources (merged)
  ansible.platform.organization:
    config:
      - name: "my-organization"
    state: merged

- name: Gather current organization state
  ansible.platform.organization:
    state: gathered
  register: result

- name: Delete specific organization resources
  ansible.platform.organization:
    config:
      - name: "my-organization"
    state: deleted

- name: Override — ensure only these organization resources exist
  ansible.platform.organization:
    config:
      - name: "keep-this-organization"
    state: overridden
"""

RETURN = """
before:
  description: The state of the organization resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the organization resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered organization resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
