#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: role_definition
short_description: Manage gateway role_definition resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway role_definition resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of role_definition resource configurations.
        - Each entry represents a desired role_definition state.
      type: list
      elements: dict
      suboptions:
        permissions:
          required: true
          type: str
          description: The permissions of the RoleDefinition.
        name:
          required: true
          type: str
          description: The name of this role.
        content_type:
          type: str
          description: String to use for references to this type from other models in the API.
        description:
          type: str
          description: A description of this role.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create role_definition resources (merged)
  ansible.platform.role_definition:
    config:
      - name: "my-role_definition"
    state: merged

- name: Gather current role_definition state
  ansible.platform.role_definition:
    state: gathered
  register: result

- name: Delete specific role_definition resources
  ansible.platform.role_definition:
    config:
      - name: "my-role_definition"
    state: deleted

- name: Override — ensure only these role_definition resources exist
  ansible.platform.role_definition:
    config:
      - name: "keep-this-role_definition"
    state: overridden
"""

RETURN = """
before:
  description: The state of the role_definition resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the role_definition resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered role_definition resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
