#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: role_user_assignment
short_description: Manage gateway role_user_assignment resources.
description:
    - Create, update, delete, or gather automation platform gateway role_user_assignment resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of role_user_assignment resource configurations.
        - Each entry represents a desired role_user_assignment state.
      type: list
      elements: dict
      suboptions:
        role_definition:
          required: true
          type: int
          description: The role definition which defines permissions conveyed by this assignment.
        object_id:
          type: str
          description: The primary key of the object this assignment applies to; null value indicates system-wide assignment.
        object_ansible_id:
          type: str
          description: The resource id of the object this role applies to. An alternative to the object_id field.
        user:
          type: int
          description: The user of the RoleUserAssignment.
        user_ansible_id:
          type: str
          description: The resource ID of the user who will receive permissions from this assignment. An alternative to user field.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create role_user_assignment resources (merged)
  ansible.platform.role_user_assignment:
    config:
      - name: "my-role_user_assignment"
    state: merged

- name: Gather current role_user_assignment state
  ansible.platform.role_user_assignment:
    state: gathered
  register: result

- name: Delete specific role_user_assignment resources
  ansible.platform.role_user_assignment:
    config:
      - name: "my-role_user_assignment"
    state: deleted

- name: Override — ensure only these role_user_assignment resources exist
  ansible.platform.role_user_assignment:
    config:
      - name: "keep-this-role_user_assignment"
    state: overridden
"""

RETURN = """
before:
  description: The state of the role_user_assignment resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the role_user_assignment resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered role_user_assignment resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
