#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: route
short_description: Manage gateway route resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway route resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of route resource configurations.
        - Each entry represents a desired route state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        http_port:
          required: true
          type: int
          description: The port on the AAP gateway to listen to traffic on.
        service_cluster:
          required: true
          type: int
          description: The AAP Service to route traffic to.
        service_port:
          required: true
          type: int
          description: The port on the service cluster to route traffic to.
        is_service_https:
          required: true
          type: bool
          description: Set this to true if the service cluster requires HTTPS.
        service_path:
          required: true
          type: str
          description: The URL path on the AAP Service cluster to route traffic to.
        gateway_path:
          required: true
          type: str
          description: The path on the AAP gateway to listen to traffic on.
        is_internal_route:
          type: bool
          description: If true, the AAP gateway will only allow other AAP services to access this route. Requires gateway auth to be enabled.
        description:
          type: str
          description: A description of this route.
        enable_gateway_auth:
          type: bool
          description: If false, the AAP gateway will not insert a gateway token into the proxied request.
        node_tags:
          type: str
          description: A comma-separated list of nodes in the service cluster to receive traffic from this route.  Leave blank to select all nodes.
        enable_mtls:
          type: bool
          description: If true, the route requires mutual TLS. Connecting clients have to provide one or more certificates.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create route resources (merged)
  ansible.platform.route:
    config:
      - name: "my-route"
    state: merged

- name: Gather current route state
  ansible.platform.route:
    state: gathered
  register: result

- name: Delete specific route resources
  ansible.platform.route:
    config:
      - name: "my-route"
    state: deleted

- name: Override — ensure only these route resources exist
  ansible.platform.route:
    config:
      - name: "keep-this-route"
    state: overridden
...
"""

RETURN = """
before:
  description: The state of the route resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the route resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered route resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
