#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: service_key
short_description: Manage gateway service_key resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway service_key resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of service_key resource configurations.
        - Each entry represents a desired service_key state.
      type: list
      elements: dict
      suboptions:
        service_cluster:
          required: true
          type: int
          description: The service cluster this key is for
        mark_previous_inactive:
          required: true
          type: bool
          description: The mark_previous_inactive of the ServiceKey.
        name:
          type: str
          description: The name of this resource.
        is_active:
          type: bool
          description: Is this service key active.
        algorithm:
          type: str
          description:
            - "HS256 - HMAC with SHA256"
            - "HS384 - HMAC with SHA384"
            - "HS512 - HMAC with SHA512"
        secret_length:
          type: int
          description: The secret_length of the ServiceKey.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create service_key resources (merged)
  ansible.platform.service_key:
    config:
      - name: "my-service_key"
    state: merged

- name: Gather current service_key state
  ansible.platform.service_key:
    state: gathered
  register: result

- name: Delete specific service_key resources
  ansible.platform.service_key:
    config:
      - name: "my-service_key"
    state: deleted

- name: Override — ensure only these service_key resources exist
  ansible.platform.service_key:
    config:
      - name: "keep-this-service_key"
    state: overridden
...
"""

RETURN = """
before:
  description: The state of the service_key resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the service_key resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered service_key resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
