#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: service_node
short_description: Manage gateway service_node resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway service_node resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of service_node resource configurations.
        - Each entry represents a desired service_node state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        address:
          required: true
          type: str
          description: The network address to route traffic for this service to.
        service_cluster:
          required: true
          type: int
          description: The AAP Service cluster that this node belongs to.
        tags:
          type: str
          description: A comma-separated list of roles to assign to a node; to be selective about which routes point to it.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create service_node resources (merged)
  ansible.platform.service_node:
    config:
      - name: "my-service_node"
    state: merged

- name: Gather current service_node state
  ansible.platform.service_node:
    state: gathered
  register: result

- name: Delete specific service_node resources
  ansible.platform.service_node:
    config:
      - name: "my-service_node"
    state: deleted

- name: Override — ensure only these service_node resources exist
  ansible.platform.service_node:
    config:
      - name: "keep-this-service_node"
    state: overridden
"""

RETURN = """
before:
  description: The state of the service_node resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the service_node resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered service_node resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
