#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: service_cluster
short_description: Manage gateway service_cluster resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway service_cluster resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of service_cluster resource configurations.
        - Each entry represents a desired service_cluster state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        service_type:
          required: true
          type: int
          description: The AAP service type of this service cluster.
        auth_type:
          type: str
          description:
            - The authorization type for this service.
            - '`JWT` - JWT'
            - '`BASIC` - Basic auth'
            - '`TOKEN` - Bearer token'

        upstream_hostname:
          type: str
          description: Set this value to enable server name identification on associated routes.
        dns_discovery_type:
          type: str
          description:
            - The DNS service discovery type for this service.
            - '`LOGICAL_DNS` - Logical DNS'
            - '`STRICT_DNS` - Strict DNS'

        dns_lookup_family:
          type: str
          description:
            - DNS lookup type for this service.
            - '`V4_ONLY` - IPv4 only'
            - '`V6_ONLY` - IPv6 only'
            - '`AUTO` - Auto (IPv6 preferred)'
            - '`ALL` - All IPv4 and IPv6 addresses'
            - '`V4_PREFERRED` - IPv4 preferred'

        outlier_detection_enabled:
          type: bool
          description: If true, outlier detection will be used to determine if a node is unhealthy and should be ejected from the cluster.
        outlier_detection_consecutive_5xx:
          type: int
          description: The number of consecutive 5xx responses to consider a node unhealthy.
        outlier_detection_interval_seconds:
          type: int
          description: The time interval between ejection analysis sweeps.
        outlier_detection_base_ejection_time_seconds:
          type: int
          description: The base time a node will be ejected for.
        outlier_detection_max_ejection_percent:
          type: int
          description: The maximum percent of nodes that can be ejected from the cluster.
        health_checks_enabled:
          type: bool
          description: If true, health checks will be used to determine if a node is healthy.
        health_check_timeout_seconds:
          type: int
          description: The time to wait for a health check to complete.
        health_check_interval_seconds:
          type: int
          description: The time between health check requests.
        health_check_unhealthy_threshold:
          type: int
          description: The number of consecutive failed health checks before a node is considered unhealthy.
        health_check_healthy_threshold:
          type: int
          description: The number of consecutive successful health checks before a node is considered healthy.
        healthy_panic_threshold:
          type: int
          description: The percentage of failed hosts when the proxy will panic and start routing traffic to all nodes. Set to 0 to disable this.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create service_cluster resources (merged)
  ansible.platform.service_cluster:
    config:
      - name: "my-service_cluster"
    state: merged

- name: Gather current service_cluster state
  ansible.platform.service_cluster:
    state: gathered
  register: result

- name: Delete specific service_cluster resources
  ansible.platform.service_cluster:
    config:
      - name: "my-service_cluster"
    state: deleted

- name: Override — ensure only these service_cluster resources exist
  ansible.platform.service_cluster:
    config:
      - name: "keep-this-service_cluster"
    state: overridden
"""

RETURN = """
before:
  description: The state of the service_cluster resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the service_cluster resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered service_cluster resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
