#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: service_type
short_description: Manage gateway service_type resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway service_type resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of service_type resource configurations.
        - Each entry represents a desired service_type state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        login_path:
          type: str
          description: API path to login for service, ex. /v1/auth/session/login/
        logout_path:
          type: str
          description: API path to logout for service, ex. /logout/
        ping_url:
          type: str
          description: URL to the ping/status page of the service, ex. /pulp/api/v3/status/
        service_index_path:
          type: str
          description: API path to resource service index endpoint, ex. /v2/service-index/
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create service_type resources (merged)
  ansible.platform.service_type:
    config:
      - name: "my-service_type"
    state: merged

- name: Gather current service_type state
  ansible.platform.service_type:
    state: gathered
  register: result

- name: Delete specific service_type resources
  ansible.platform.service_type:
    config:
      - name: "my-service_type"
    state: deleted

- name: Override — ensure only these service_type resources exist
  ansible.platform.service_type:
    config:
      - name: "keep-this-service_type"
    state: overridden
"""

RETURN = """
before:
  description: The state of the service_type resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the service_type resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered service_type resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
