#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: settings
short_description: Manage gateway setting resources.
description:
    - Create, update, delete, or gather automation platform gateway setting resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of setting resource configurations.
        - Each entry represents a desired setting state.
      type: list
      elements: dict
      suboptions:
        settings:
          type: dict
          description: >
            A flat dict of gateway settings to apply, e.g.
            C({SESSION_COOKIE_AGE: 3600}). Keys and values are passed
            directly to the settings PATCH endpoint.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create setting resources (merged)
  ansible.platform.settings:
    config:
      - name: "my-setting"
    state: merged

- name: Gather current setting state
  ansible.platform.settings:
    state: gathered
  register: result

- name: Delete specific setting resources
  ansible.platform.settings:
    config:
      - name: "my-setting"
    state: deleted

- name: Override — ensure only these setting resources exist
  ansible.platform.settings:
    config:
      - name: "keep-this-setting"
    state: overridden
"""

RETURN = """
before:
  description: The state of the setting resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the setting resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered setting resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
