#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: team
short_description: Manage gateway team resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway team resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of team resource configurations.
        - Each entry represents a desired team state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        organization:
          required: true
          type: int
          description: The organization of this team.
        description:
          type: str
          description: The team description.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create team resources (merged)
  ansible.platform.team:
    config:
      - name: "my-team"
    state: merged

- name: Gather current team state
  ansible.platform.team:
    state: gathered
  register: result

- name: Delete specific team resources
  ansible.platform.team:
    config:
      - name: "my-team"
    state: deleted

- name: Override — ensure only these team resources exist
  ansible.platform.team:
    config:
      - name: "keep-this-team"
    state: overridden
...
"""

RETURN = """
before:
  description: The state of the team resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the team resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered team resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
