#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: tokens
short_description: Manage gateway token resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway token resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of token resource configurations.
        - Each entry represents a desired token state.
      type: list
      elements: dict
      suboptions:
        application:
          type: int
          description: The related application. If None, this is a user token instead of an application token.
        description:
          type: str
          description: A description for this token.
        scope:
          type: str
          description: Allowed scopes, further restricts user permissions. Must be a simple space-separated string with allowed scopes ['read', 'write'].
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create token resources (merged)
  ansible.platform.tokens:
    config:
      - name: "my-token"
    state: merged

- name: Gather current token state
  ansible.platform.tokens:
    state: gathered
  register: result

- name: Delete specific token resources
  ansible.platform.tokens:
    config:
      - name: "my-token"
    state: deleted

- name: Override — ensure only these token resources exist
  ansible.platform.tokens:
    config:
      - name: "keep-this-token"
    state: overridden
...
"""

RETURN = """
before:
  description: The state of the token resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the token resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered token resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
