#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: ui_plugin_route
short_description: Manage gateway ui_plugin_route resources.
description:
    - Create, update, delete, or gather automation platform gateway ui_plugin_route resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of ui_plugin_route resource configurations.
        - Each entry represents a desired ui_plugin_route state.
      type: list
      elements: dict
      suboptions:
        name:
          required: true
          type: str
          description: The name of this resource.
        http_port:
          required: true
          type: int
          description: The port on the AAP gateway to listen to traffic on.
        service_cluster:
          required: true
          type: int
          description: The service_cluster of the UiPluginRoute.
        service_port:
          required: true
          type: int
          description: The port on the service cluster to route traffic to.
        is_service_https:
          required: true
          type: bool
          description: Set this to true if the service cluster requires HTTPS.
        ui_plugin_path:
          required: true
          type: str
          description: The relative path to the UI plugin on the service cluster.
        description:
          type: str
          description: A description of this route.
        order:
          type: int
          description: The order to apply the routes in; lower numbers are first. Items with the same value have no guaranteed order
        node_tags:
          type: str
          description: A comma-separated list of nodes in the service cluster to receive traffic from this route.  Leave blank to select all nodes.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create ui_plugin_route resources (merged)
  ansible.platform.ui_plugin_route:
    config:
      - name: "my-ui_plugin_route"
    state: merged

- name: Gather current ui_plugin_route state
  ansible.platform.ui_plugin_route:
    state: gathered
  register: result

- name: Delete specific ui_plugin_route resources
  ansible.platform.ui_plugin_route:
    config:
      - name: "my-ui_plugin_route"
    state: deleted

- name: Override — ensure only these ui_plugin_route resources exist
  ansible.platform.ui_plugin_route:
    config:
      - name: "keep-this-ui_plugin_route"
    state: overridden
"""

RETURN = """
before:
  description: The state of the ui_plugin_route resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the ui_plugin_route resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered ui_plugin_route resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
