#!/usr/bin/python
# coding: utf-8 -*-
# (c) 2025, Ansible Platform Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
Auto-generated by tools/generate_resource.py — review before committing.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = """
---
module: users
short_description: Manage gateway user resources.
author: Red Hat (@RedHatOfficial)
description:
    - Create, update, delete, or gather automation platform gateway user resources.
    - Follows the Ansible resource module pattern with before/after state tracking.
options:
    config:
      description:
        - A list of user resource configurations.
        - Each entry represents a desired user state.
      type: list
      elements: dict
      suboptions:
        username:
          required: true
          type: str
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
        email:
          type: str
          description: The email of the User.
        first_name:
          type: str
          description: The first_name of the User.
        last_name:
          type: str
          description: The last_name of the User.
        password:
          type: str
          description: The password of the User.
        is_superuser:
          type: bool
          description: Designates that this user has all permissions without explicitly assigning them.
        authenticators:
          type: str
          description: "DEPRECATED: This field is deprecated and will be removed in a future version. Please use 'associated_authenticators' instead."
        authenticator_uid:
          type: str
          description: "DEPRECATED: This field is deprecated and will be removed in a future version. Please use 'associated_authenticators' instead."
        associated_authenticators:
          type: str
          description: The associated_authenticators of the User.
        id:
          type: str
          description: The unique identifier of the resource. Used for update/delete operations.

extends_documentation_fragment:
  - ansible.platform.auth
  - ansible.platform.state
"""

EXAMPLES = """
- name: Create user resources (merged)
  ansible.platform.users:
    config:
      - username: "my-user"
    state: merged

- name: Gather current user state
  ansible.platform.users:
    state: gathered
  register: result

- name: Delete specific user resources
  ansible.platform.users:
    config:
      - username: "my-user"
    state: deleted

- name: Override — ensure only these user resources exist
  ansible.platform.users:
    config:
      - username: "keep-this-user"
    state: overridden
...
"""

RETURN = """
before:
  description: The state of the user resources before this run.
  returned: when state is not gathered
  type: list
  elements: dict
after:
  description: The state of the user resources after this run.
  returned: when state is not gathered
  type: list
  elements: dict
gathered:
  description: The gathered user resource state (read-only).
  returned: when state is gathered
  type: list
  elements: dict
config:
  description: The resulting configuration (alias for after or gathered).
  returned: always
  type: list
  elements: dict
"""
